const REGISTRATION_FEE_PER_PARTICIPANT = 350;
const CURRENCY = 'INR';

const MIN_TEAM_MEMBERS = 1;
const MAX_TEAM_MEMBERS = 6;

const STUDENT_TYPES = Object.freeze({
  HOSTEL: 'HOSTEL',
  DAY_SCHOLAR: 'DAY_SCHOLAR',
});

const PAYMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
});

const PAYMENT_PROVIDERS = Object.freeze({
  MOCK: 'mock',
  RAZORPAY: 'razorpay',
});

const ADMIN_ROLES = Object.freeze({
  ADMIN: 'admin',
});

const WEBHOOK_EVENTS = Object.freeze({
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  IGNORED: 'IGNORED',
});

const ERROR_CODES = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PARTICIPANT_COUNT: 'INVALID_PARTICIPANT_COUNT',
  DUPLICATE_PARTICIPANT: 'DUPLICATE_PARTICIPANT',
  BLOCKED_REGISTER_NUMBER: 'BLOCKED_REGISTER_NUMBER',
  PAYMENT_ALREADY_COMPLETED: 'PAYMENT_ALREADY_COMPLETED',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_ORDER_NOT_FOUND: 'PAYMENT_ORDER_NOT_FOUND',
});

module.exports = {
  REGISTRATION_FEE_PER_PARTICIPANT,
  CURRENCY,
  MIN_TEAM_MEMBERS,
  MAX_TEAM_MEMBERS,
  STUDENT_TYPES,
  PAYMENT_STATUSES,
  PAYMENT_PROVIDERS,
  ADMIN_ROLES,
  WEBHOOK_EVENTS,
  ERROR_CODES,
};
